title=Custom Spring Boot Shell Banner
date=2016-03-24
type=post
tags=blog,groovy,spring
status=published
~~~~~~
I did a http://dfw2gug.org/blog/2016/march-2016.html[Groovy User Group talk] recently related to my http://coffeaelectronica.com/blog/2015/spring-shell.html[Spring Boot Remote Shell] blog post and while putting the talk together I stumbled across a bug in the integration between Spring Boot and the Crash shell (see https:///github.com/spring-projects/spring-boot/issues/3988[Spring-Boot-3988]). The custom banner you can add to your Spring Boot application (as /resources/banner.txt) is not applied by default to your crash shell, so you get the boring Spring logo every time you startup the shell. I had worked with the Crash shell previously and I remember that the banner was customizable so I did a little digging and figured out how to code a work-around - I also added this information to the bug ticket; I considered contributing a pull request, but I am not sure how this would be coded into the default application framework.

The work-around is pretty simple and straight-forward if you have worked with the crash shell before. You use their method of customization and then have it pull in your Spring Boot custom banner. In your `/src/main/resources/commands` directory you add a `login.groovy` file, which Crash will load with every shell connection. The file allows the customization of the banner and the prompt. We can then load our spring banner from the classpath. The basic code is as follows:

[source,groovy]
.login.groovy
----
welcome = { ->
    def hostName;
    try {
        hostName = java.net.InetAddress.getLocalHost().getHostName();
    } catch (java.net.UnknownHostException ignore) {
        hostName = 'localhost';
    }

    String banner = YourApplication.getResourceAsStream('/banner.txt').text

    return """
${banner}
Logged into $hostName @ ${new Date()}
"""
}

prompt = { ->
    return "% ";
}
----

It's a silly little thing to worry about, but sometimes it's the little things that make an application feel more like your own.
